# Generated by Django 3.2.8 on 2021-10-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotespage', '0007_auto_20170329_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='api_key',
            field=models.CharField(max_length=64, unique=True, verbose_name='API key'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='speaker_class',
            field=models.CharField(choices=[('FAC', 'Faculty'), ('GS', 'Graduate Student'), ('INV', 'Invited Speaker'), ('OTH', 'Other')], default='FAC', max_length=3),
        ),
    ]
